platform :ios, '13.0'

flutter_application_path = '../native_grayscale_sdk/flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

project 'NativeGrayscaleSample.xcodeproj'

target 'NativeGrayscaleSample' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
